create table departments (
dept_id serial primary key,
dept_name varchar unique not null,
location varchar not null,
employee_limit int not null check (employee_limit >0)
);

select * from departments;

INSERT INTO departments (dept_name, location, employee_limit) VALUES
('Web Development', 'Nagpur', 20),
('Mobile App Development', 'Pune', 15),
('Software Testing', 'Nagpur', 12),
('UI/UX Design', 'Mumbai', 10),
('Cloud Services', 'Hyderabad', 18),
('Digital Marketing', 'Nagpur', 25),
('Data Analytics', 'Bangalore', 14),
('AI & ML Research', 'Hyderabad', 10),
('Network Security', 'Pune', 12),
('Technical Support', 'Nagpur', 30),
('HR & Recruitment', 'Nagpur', 8),
('Finance & Accounts', 'Mumbai', 10),
('Sales', 'Delhi', 22),
('Business Development', 'Nagpur', 18),
('Client Relations', 'Bangalore', 15),
('Graphic Design', 'Nagpur', 10),
('Content Writing', 'Pune', 12),
('SEO Optimization', 'Nagpur', 10),
('Social Media Marketing', 'Mumbai', 15),
('DevOps', 'Hyderabad', 16),
('IT Infrastructure', 'Bangalore', 14),
('R&D Department', 'Pune', 8),
('Quality Assurance', 'Nagpur', 10),
('Training & Development', 'Nagpur', 12),
('Customer Success', 'Mumbai', 18),
('Operations', 'Hyderabad', 20),
('Legal & Compliance', 'Delhi', 6),
('Cybersecurity', 'Bangalore', 10),
('System Administration', 'Nagpur', 14),
('Product Management', 'Pune', 10),
('ERP Solutions', 'Mumbai', 8),
('CRM Solutions', 'Nagpur', 10),
('Data Engineering', 'Hyderabad', 12),
('Backend Development', 'Bangalore', 15),
('Frontend Development', 'Nagpur', 12),
('Blockchain Development', 'Pune', 10),
('Embedded Systems', 'Hyderabad', 8),
('AR/VR Development', 'Mumbai', 6),
('IoT Solutions', 'Bangalore', 10),
('Game Development', 'Nagpur', 14),
('Customer Support', 'Pune', 20),
('Project Management', 'Nagpur', 10),
('Server Maintenance', 'Hyderabad', 8),
('Automation', 'Bangalore', 12),
('UI Prototyping', 'Mumbai', 6),
('Database Administration', 'Pune', 10),
('Technical Documentation', 'Nagpur', 8),
('Email Marketing', 'Mumbai', 12),
('Helpdesk', 'Nagpur', 15),
('Innovation Lab', 'Hyderabad', 6);
